/**
 * Swagger Code Linker
 *
 * Links swagger/OpenAPI specifications to code entities (controllers, generated clients, types).
 * Follows the pattern from src/parsers/ngrx/builders.ts.
 *
 * Detection strategies:
 * 1. Producers: Controllers/routes that create the API (NestJS, Express, Spring Boot, .NET)
 * 2. Consumers: Generated clients (openapi-generator, NSwag, Autorest, Refitter, ng-openapi-gen)
 * 3. Schema↔Type matching: Links swagger schemas to code types by name/properties
 */

import { log } from "../../logging/index.js";
import type { Entity } from "../../types/storage.js";
import { RelationType } from "../../types/storage.js";
import type {
  CodegenConfig,
  CodeRoute,
  ProducerPattern,
  SwaggerAnalysis,
  SwaggerCodeLink,
  SwaggerEndpoint,
  SwaggerRelationship,
} from "./types.js";

// =============================================================================
// CONSTANTS
// =============================================================================

/** Producer detection patterns by framework */
const PRODUCER_PATTERNS: ProducerPattern[] = [
  {
    framework: "nestjs",
    controllerDecorators: ["Controller"],
    routeDecorators: ["Get", "Post", "Put", "Patch", "Delete", "Options", "Head", "All"],
    swaggerDecorators: ["ApiOperation", "ApiResponse", "ApiTags", "ApiProperty", "ApiBody", "ApiParam", "ApiQuery"],
  },
  {
    framework: "spring-boot",
    controllerDecorators: ["RestController", "Controller"],
    routeDecorators: ["GetMapping", "PostMapping", "PutMapping", "PatchMapping", "DeleteMapping", "RequestMapping"],
    swaggerDecorators: ["Operation", "ApiResponse", "Tag", "Schema"],
  },
  {
    framework: "dotnet",
    controllerDecorators: ["ApiController", "Controller"],
    routeDecorators: ["HttpGet", "HttpPost", "HttpPut", "HttpPatch", "HttpDelete", "Route"],
    swaggerDecorators: ["ProducesResponseType", "SwaggerOperation", "SwaggerResponse"],
  },
];

/** Codegen configuration patterns */
const CODEGEN_CONFIGS: CodegenConfig[] = [
  {
    configFile: "openapitools.json",
    generator: "openapi-generator-cli",
    fileMarkers: ["/* tslint:disable */", "/* eslint-disable */", "// This file was auto-generated"],
  },
  {
    configFile: "nswag.json",
    generator: "NSwag",
    fileMarkers: ["//----------------------", "// <auto-generated>", "// This code was generated by NSwag"],
  },
  {
    configFile: ".refitter",
    generator: "Refitter",
    fileMarkers: ["// <auto-generated>", "// This code was generated by Refitter"],
  },
  {
    configFile: "ng-openapi-gen.json",
    generator: "ng-openapi-gen",
    fileMarkers: ["// @generated", "/* tslint:disable */"],
  },
  {
    configFile: "autorest.md",
    generator: "Autorest",
    fileMarkers: ["// Code generated by Microsoft", "// <auto-generated>"],
  },
  {
    configFile: "swagger-codegen-config.json",
    generator: "swagger-codegen",
    fileMarkers: ["// This file was auto-generated", "/* tslint:disable */", "@javax.annotation.Generated"],
  },
];

/** All generated file markers across all generators */
const ALL_GENERATED_MARKERS = CODEGEN_CONFIGS.flatMap((c) => c.fileMarkers);

/** Name suffixes to strip when matching schemas to types */
const TYPE_SUFFIXES = ["Dto", "DTO", "Model", "Response", "Request", "Vm", "ViewModel", "Entity", "Payload"];

// =============================================================================
// MAIN LINKER FUNCTION
// =============================================================================

/**
 * Analyze swagger↔code links from graph entities
 *
 * @param entities All entities from the graph
 * @returns SwaggerAnalysis with detected links
 */
export function analyzeSwaggerCodeLinks(entities: Entity[]): SwaggerAnalysis {
  const analysis: SwaggerAnalysis = {
    producers: [],
    consumers: [],
    generatedTypes: [],
    generatedFileMarkers: [],
    codegenConfigs: [],
  };

  // Separate swagger entities from code entities
  const swaggerEndpoints: SwaggerEndpoint[] = [];
  const swaggerSchemas: Entity[] = [];
  const swaggerSpecs: Entity[] = [];
  const codeEntities: Entity[] = [];

  for (const entity of entities) {
    const swaggerType = entity.metadata?.["swaggerType"] as string | undefined;

    if (swaggerType === "endpoint") {
      swaggerEndpoints.push({
        httpMethod: (entity.metadata?.["httpMethod"] as string) || "",
        path: (entity.metadata?.["path"] as string) || "",
        ...((entity.metadata?.["operationId"] as string)
          ? { operationId: entity.metadata["operationId"] as string }
          : {}),
        entityName: entity.name,
        filePath: entity.filePath,
      });
    } else if (swaggerType === "schema") {
      swaggerSchemas.push(entity);
    } else if (swaggerType === "api_spec") {
      swaggerSpecs.push(entity);
    } else if (!entity.metadata?.["isApiContract"]) {
      codeEntities.push(entity);
    }
  }

  // Skip if no swagger entities
  if (swaggerEndpoints.length === 0 && swaggerSchemas.length === 0) {
    return analysis;
  }

  log.i("SWAGGER_LINKER", "analyzing", {
    endpoints: swaggerEndpoints.length,
    schemas: swaggerSchemas.length,
    codeEntities: codeEntities.length,
  });

  // 1. Detect producers (controllers that create the API)
  const producers = detectProducers(codeEntities, swaggerEndpoints);
  analysis.producers = producers;

  // 2. Detect consumers (generated clients)
  const { consumers, markers, configs } = detectConsumers(codeEntities, swaggerEndpoints, swaggerSpecs);
  analysis.consumers = consumers;
  analysis.generatedFileMarkers = markers;
  analysis.codegenConfigs = configs;

  // 3. Match schemas to types
  const generatedTypes = matchSchemasToTypes(swaggerSchemas, codeEntities);
  analysis.generatedTypes = generatedTypes;

  log.i("SWAGGER_LINKER", "analysis_done", {
    producers: analysis.producers.length,
    consumers: analysis.consumers.length,
    generatedTypes: analysis.generatedTypes.length,
    configs: analysis.codegenConfigs.length,
  });

  return analysis;
}

/**
 * Build graph relationships from swagger analysis
 */
export function buildSwaggerRelationships(analysis: SwaggerAnalysis): SwaggerRelationship[] {
  const relationships: SwaggerRelationship[] = [];

  for (const link of analysis.producers) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.swaggerEntityName,
      type: RelationType.PRODUCES_API,
      fromFile: link.codeFilePath,
      toFile: link.swaggerFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        context: "controller produces API endpoint",
      },
    });
  }

  for (const link of analysis.consumers) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.swaggerEntityName,
      type: RelationType.CONSUMES_API,
      fromFile: link.codeFilePath,
      toFile: link.swaggerFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        context: "generated client consumes API endpoint",
      },
    });
  }

  for (const link of analysis.generatedTypes) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.swaggerEntityName,
      type: RelationType.GENERATED_FROM,
      fromFile: link.codeFilePath,
      toFile: link.swaggerFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        schemaName: link.swaggerEntityName,
        context: "type generated from swagger schema",
      },
    });
  }

  return relationships;
}

// =============================================================================
// PRODUCER DETECTION
// =============================================================================

/**
 * Detect controllers/routes that produce the API described in swagger
 */
function detectProducers(codeEntities: Entity[], swaggerEndpoints: SwaggerEndpoint[]): SwaggerCodeLink[] {
  const links: SwaggerCodeLink[] = [];
  if (swaggerEndpoints.length === 0) return links;

  // Extract routes from code entities
  const codeRoutes = extractCodeRoutes(codeEntities);

  // Match code routes to swagger endpoints
  for (const route of codeRoutes) {
    const match = findEndpointMatch(route, swaggerEndpoints);
    if (match) {
      links.push({
        swaggerEntityName: match.endpoint.entityName,
        codeEntityName: route.entityName,
        codeFilePath: route.filePath,
        swaggerFilePath: match.endpoint.filePath,
        linkType: "produces_api",
        confidence: match.confidence,
        evidence: match.evidence,
      });
    }
  }

  return links;
}

/**
 * Extract route information from code entities by analyzing decorators
 */
function extractCodeRoutes(entities: Entity[]): CodeRoute[] {
  const routes: CodeRoute[] = [];

  // Build a map of controller prefixes by file
  const controllerPrefixes = new Map<string, string>();

  for (const entity of entities) {
    if (!entity.metadata?.["decorators"]) continue;
    const decorators = entity.metadata["decorators"] as Array<{ name: string; arguments?: string[] }>;

    for (const pattern of PRODUCER_PATTERNS) {
      // Check for controller decorators
      const controllerDec = decorators.find((d) => pattern.controllerDecorators.includes(d.name));
      if (controllerDec) {
        const prefix = controllerDec.arguments?.[0]?.replace(/['"]/g, "") || "";
        controllerPrefixes.set(entity.filePath, prefix);
      }

      // Check for route decorators
      for (const dec of decorators) {
        const routeDecName = pattern.routeDecorators.find((rd) => rd === dec.name);
        if (routeDecName) {
          const httpMethod = extractHttpMethodFromDecorator(routeDecName, pattern.framework);
          const routePath = dec.arguments?.[0]?.replace(/['"]/g, "") || "";
          const prefix = controllerPrefixes.get(entity.filePath) || "";
          const fullPath = normalizePath(prefix, routePath);

          if (httpMethod) {
            routes.push({
              httpMethod,
              path: fullPath,
              entityName: entity.name,
              filePath: entity.filePath,
              controllerPrefix: prefix,
            });
          }
        }
      }
    }
  }

  return routes;
}

/**
 * Extract HTTP method from decorator name
 */
function extractHttpMethodFromDecorator(decoratorName: string, _framework: string): string | null {
  const lowerName = decoratorName.toLowerCase();

  // Direct method decorators
  if (lowerName.startsWith("get") || lowerName === "httpget") return "GET";
  if (lowerName.startsWith("post") || lowerName === "httppost") return "POST";
  if (lowerName.startsWith("put") || lowerName === "httpput") return "PUT";
  if (lowerName.startsWith("patch") || lowerName === "httppatch") return "PATCH";
  if (lowerName.startsWith("delete") || lowerName === "httpdelete") return "DELETE";
  if (lowerName === "options") return "OPTIONS";
  if (lowerName === "head") return "HEAD";

  // Spring Boot @RequestMapping needs explicit method
  if (lowerName === "requestmapping") return null; // Ambiguous, skip

  return null;
}

/**
 * Find a matching swagger endpoint for a code route
 */
function findEndpointMatch(
  route: CodeRoute,
  endpoints: SwaggerEndpoint[],
): { endpoint: SwaggerEndpoint; confidence: number; evidence: string[] } | null {
  let bestMatch: { endpoint: SwaggerEndpoint; confidence: number; evidence: string[] } | null = null;

  for (const endpoint of endpoints) {
    const evidence: string[] = [];
    let confidence = 0;

    // Match HTTP method
    if (route.httpMethod === endpoint.httpMethod) {
      confidence += 0.4;
      evidence.push(`HTTP method match: ${route.httpMethod}`);
    } else {
      continue; // Skip if method doesn't match
    }

    // Match path
    const pathScore = compareEndpointPaths(route.path, endpoint.path);
    if (pathScore > 0) {
      confidence += pathScore * 0.6;
      evidence.push(`Path match (${(pathScore * 100).toFixed(0)}%): ${route.path} ↔ ${endpoint.path}`);
    } else {
      continue; // Skip if path doesn't match at all
    }

    if (confidence > (bestMatch?.confidence ?? 0)) {
      bestMatch = { endpoint, confidence: Math.min(1, confidence), evidence };
    }
  }

  return bestMatch && bestMatch.confidence >= 0.5 ? bestMatch : null;
}

/**
 * Compare two endpoint paths, returning a score 0-1
 */
function compareEndpointPaths(codePath: string, swaggerPath: string): number {
  const normCode = normalizeEndpointPath(codePath);
  const normSwagger = normalizeEndpointPath(swaggerPath);

  if (normCode === normSwagger) return 1.0;

  // Compare segments
  const codeSegments = normCode.split("/").filter(Boolean);
  const swaggerSegments = normSwagger.split("/").filter(Boolean);

  if (codeSegments.length !== swaggerSegments.length) return 0;

  let matchCount = 0;
  for (let i = 0; i < codeSegments.length; i++) {
    const cs = codeSegments[i]!;
    const ss = swaggerSegments[i]!;

    if (cs === ss) {
      matchCount++;
    } else if (isPathParam(cs) && isPathParam(ss)) {
      matchCount++; // Both are parameters
    } else {
      return 0; // Structural mismatch
    }
  }

  return matchCount / codeSegments.length;
}

/**
 * Normalize endpoint path for comparison
 * - Strips leading/trailing slashes
 * - Converts {id} to :id and vice versa to a common form
 */
function normalizeEndpointPath(path: string): string {
  return path
    .replace(/^\/|\/$/g, "") // Strip leading/trailing slashes
    .replace(/\{(\w+)\}/g, ":$1") // {id} → :id
    .toLowerCase();
}

/**
 * Check if a path segment is a parameter
 */
function isPathParam(segment: string): boolean {
  return segment.startsWith(":") || segment.startsWith("{");
}

/**
 * Normalize and join controller prefix and route path
 */
function normalizePath(prefix: string, routePath: string): string {
  const parts = [prefix, routePath].filter(Boolean);
  const joined = parts.join("/").replace(/\/+/g, "/");
  return joined.startsWith("/") ? joined : `/${joined}`;
}

// =============================================================================
// CONSUMER DETECTION
// =============================================================================

/**
 * Detect generated clients that consume the API
 */
function detectConsumers(
  codeEntities: Entity[],
  swaggerEndpoints: SwaggerEndpoint[],
  swaggerSpecs: Entity[],
): { consumers: SwaggerCodeLink[]; markers: string[]; configs: string[] } {
  const consumers: SwaggerCodeLink[] = [];
  const foundMarkers: string[] = [];
  const foundConfigs: string[] = [];

  // Detect codegen configs from entities (these are parsed from package.json scripts, file entities, etc.)
  for (const entity of codeEntities) {
    const entityName = entity.name.toLowerCase();
    const filePath = entity.filePath.toLowerCase();

    // Check for codegen config files
    for (const config of CODEGEN_CONFIGS) {
      if (entityName === config.configFile || filePath.endsWith(`/${config.configFile}`)) {
        foundConfigs.push(config.configFile);
      }
    }

    // Check for codegen scripts in package.json
    if (entity.metadata?.["scriptCommand"]) {
      const cmd = String(entity.metadata["scriptCommand"]).toLowerCase();
      if (
        cmd.includes("openapi-generator") ||
        cmd.includes("nswag") ||
        cmd.includes("autorest") ||
        cmd.includes("refitter") ||
        cmd.includes("ng-openapi-gen") ||
        cmd.includes("swagger-codegen")
      ) {
        foundConfigs.push(`script:${entity.name}`);
      }
    }
  }

  // Find generated files by markers in entity metadata
  const generatedFiles = new Set<string>();
  for (const entity of codeEntities) {
    if (entity.metadata?.["isGenerated"] || entity.metadata?.["autoGenerated"]) {
      generatedFiles.add(entity.filePath);
    }

    // Check entity name patterns typical for generated clients
    const name = entity.name;
    if ((name.endsWith("Client") || name.endsWith("Service") || name.endsWith("Api")) && isLikelyGenerated(entity)) {
      generatedFiles.add(entity.filePath);

      // Try to match generated methods to swagger endpoints
      const swaggerFile = swaggerSpecs[0]?.filePath;
      if (swaggerFile) {
        for (const endpoint of swaggerEndpoints) {
          // Match by operation ID or method name similarity
          if (
            endpoint.operationId &&
            (name.includes(endpoint.operationId) ||
              entity.name.toLowerCase().includes(endpoint.operationId.toLowerCase()))
          ) {
            consumers.push({
              swaggerEntityName: endpoint.entityName,
              codeEntityName: entity.name,
              codeFilePath: entity.filePath,
              swaggerFilePath: swaggerFile,
              linkType: "consumes_api",
              confidence: 0.7,
              evidence: [`Operation ID match: ${endpoint.operationId}`, `Generated client pattern: ${name}`],
            });
            foundMarkers.push(`operationId:${endpoint.operationId}`);
          }
        }
      }
    }
  }

  return { consumers, markers: foundMarkers, configs: foundConfigs };
}

/**
 * Check if an entity is likely auto-generated
 */
function isLikelyGenerated(entity: Entity): boolean {
  // Check metadata flags
  if (entity.metadata?.["isGenerated"] || entity.metadata?.["autoGenerated"]) return true;

  // Check file path patterns
  const path = entity.filePath.toLowerCase();
  if (
    path.includes("/generated/") ||
    path.includes("/gen/") ||
    path.includes("/auto-generated/") ||
    path.includes("/__generated__/")
  ) {
    return true;
  }

  return false;
}

// =============================================================================
// SCHEMA ↔ TYPE MATCHING
// =============================================================================

/**
 * Match swagger schemas to code types
 */
function matchSchemasToTypes(swaggerSchemas: Entity[], codeEntities: Entity[]): SwaggerCodeLink[] {
  const links: SwaggerCodeLink[] = [];

  // Collect code types (interfaces, types, classes that could be DTOs)
  const codeTypes = codeEntities.filter((e) => e.type === "interface" || e.type === "type" || e.type === "class");

  for (const schema of swaggerSchemas) {
    const schemaName = schema.name;
    const schemaProps = extractSchemaPropertyNames(schema);

    let bestMatch: {
      entity: Entity;
      confidence: number;
      evidence: string[];
    } | null = null;

    for (const codeType of codeTypes) {
      const evidence: string[] = [];
      let confidence = 0;

      // 1. Exact name match
      if (codeType.name === schemaName || codeType.name.split(".").pop() === schemaName) {
        confidence += 0.6;
        evidence.push(`Exact name match: ${schemaName}`);
      } else {
        // 2. Name match without suffix
        const strippedName = stripTypeSuffix(codeType.name.split(".").pop() || codeType.name);
        if (strippedName === schemaName) {
          confidence += 0.4;
          evidence.push(`Name match without suffix: ${codeType.name} → ${schemaName}`);
        } else {
          continue; // No name match, skip
        }
      }

      // 3. Property comparison (if both have properties)
      if (schemaProps.length > 0) {
        const codeProps = extractCodePropertyNames(codeType);
        if (codeProps.length > 0) {
          const overlap = schemaProps.filter((sp) => codeProps.includes(sp));
          const propScore = overlap.length / Math.max(schemaProps.length, 1);
          if (propScore >= 0.7) {
            confidence += 0.3;
            evidence.push(
              `Property overlap: ${overlap.length}/${schemaProps.length} (${(propScore * 100).toFixed(0)}%)`,
            );
          } else if (propScore >= 0.3) {
            confidence += 0.1;
            evidence.push(`Partial property overlap: ${overlap.length}/${schemaProps.length}`);
          }
        }
      }

      // Check if code type is generated
      if (isLikelyGenerated(codeType)) {
        confidence += 0.1;
        evidence.push("File in generated path");
      }

      if (confidence > (bestMatch?.confidence ?? 0)) {
        bestMatch = { entity: codeType, confidence: Math.min(1, confidence), evidence };
      }
    }

    if (bestMatch && bestMatch.confidence >= 0.4) {
      links.push({
        swaggerEntityName: schemaName,
        codeEntityName: bestMatch.entity.name,
        codeFilePath: bestMatch.entity.filePath,
        swaggerFilePath: schema.filePath,
        linkType: "generated_from",
        confidence: bestMatch.confidence,
        evidence: bestMatch.evidence,
      });
    }
  }

  return links;
}

/**
 * Extract property names from a swagger schema entity
 */
function extractSchemaPropertyNames(schema: Entity): string[] {
  const props = schema.metadata?.["properties"];
  if (!Array.isArray(props)) return [];
  return props.map((p: { name?: string }) => p.name).filter((n): n is string => typeof n === "string");
}

/**
 * Extract property names from a code type entity
 */
function extractCodePropertyNames(entity: Entity): string[] {
  // Check parameters (for interfaces/types with listed fields)
  if (entity.metadata?.["parameters"] && Array.isArray(entity.metadata["parameters"])) {
    return entity.metadata["parameters"]
      .map((p: { name?: string }) => p.name)
      .filter((n): n is string => typeof n === "string");
  }

  // Check properties metadata
  if (entity.metadata?.["properties"] && Array.isArray(entity.metadata["properties"])) {
    return entity.metadata["properties"]
      .map((p: { name?: string }) => p.name)
      .filter((n): n is string => typeof n === "string");
  }

  return [];
}

/**
 * Strip common type suffixes for name matching
 */
function stripTypeSuffix(name: string): string {
  for (const suffix of TYPE_SUFFIXES) {
    if (name.endsWith(suffix) && name.length > suffix.length) {
      return name.slice(0, -suffix.length);
    }
  }
  return name;
}

// =============================================================================
// EXPORTS FOR GENERATED CODE MARKERS
// =============================================================================

/**
 * Get all known generated code markers
 */
export function getGeneratedCodeMarkers(): string[] {
  return ALL_GENERATED_MARKERS;
}

/**
 * Get all known codegen config file names
 */
export function getCodegenConfigFiles(): string[] {
  return CODEGEN_CONFIGS.map((c) => c.configFile);
}
