/**
 * AutoDoc Manager
 *
 * Central manager for AutoDoc functionality.
 * Integrates DocStorage, RefStorage, and GraphStorage.
 *
 * Architecture References:
 * - DocStorage: src/autodoc/storage/doc-storage.ts
 * - RefStorage: src/autodoc/storage/ref-storage.ts
 * - GraphStorage: src/storage/graph-storage.ts
 */

import type { ProjectContext } from "../../storage/libsql/types.js";
import type { GraphStorage, Relationship } from "../../types/storage.js";
import { mapParallel } from "../../utils/parallel.js";
import { flattenSections, parseMarkdown } from "../parser/md-parser.js";
import type {
  AutoDocConfig,
  AutoDocStatus,
  AutoDocTodo,
  DocContext,
  DocEntity,
  DocEntityType,
  OutdatedDoc,
  Reference,
} from "../types.js";
import { type ChangeType, RefSourceType, RefTargetType, RefType } from "../types.js";
import { DocStorage } from "./doc-storage.js";
import { RefStorage } from "./ref-storage.js";

// =============================================================================
// 1. CONSTANTS
// =============================================================================

/** Default confidence threshold for outdated docs */
const OUTDATED_THRESHOLD = 0.7;

// =============================================================================
// 2. AUTODOC MANAGER CLASS
// =============================================================================

/**
 * Extension interface for GraphStorage with optional getIncomingRelationships method
 */
interface GraphStorageWithIncoming extends GraphStorage {
  getIncomingRelationships?: (entityId: string) => Promise<Relationship[]>;
}

export class AutoDocManager {
  private docStorage: DocStorage;
  private refStorage: RefStorage;
  private graphStorage: GraphStorage | null = null;
  private initialized = false;
  private config: AutoDocConfig | null = null;

  constructor(dbPath: string) {
    this.docStorage = new DocStorage(dbPath);
    this.refStorage = new RefStorage(dbPath);
  }

  /**
   * Initialize the AutoDoc manager
   */
  async initialize(graphStorage?: GraphStorage): Promise<void> {
    if (this.initialized) return;

    await this.docStorage.initialize();
    await this.refStorage.initialize();

    if (graphStorage) {
      this.graphStorage = graphStorage;
    }

    this.initialized = true;
  }

  /**
   * Set GraphStorage for entity lookups
   */
  setGraphStorage(graphStorage: GraphStorage): void {
    this.graphStorage = graphStorage;
  }

  /**
   * Set project context for branch isolation
   */
  setProjectContext(context: ProjectContext): void {
    this.docStorage.setProjectContext(context);
    this.refStorage.setProjectContext(context);
  }

  /**
   * Check if AutoDoc is initialized
   */
  isInitialized(): boolean {
    return this.initialized;
  }

  // ---------------------------------------------------------------------------
  // Configuration
  // ---------------------------------------------------------------------------

  /**
   * Set AutoDoc configuration
   */
  setConfig(config: AutoDocConfig): void {
    this.config = config;
  }

  /**
   * Get AutoDoc configuration
   */
  getConfig(): AutoDocConfig | null {
    return this.config;
  }

  /**
   * Get AutoDoc status
   */
  async getStatus(): Promise<AutoDocStatus> {
    const docStats = await this.docStorage.getStats();
    const refStats = await this.refStorage.getStats();

    return {
      enabled: this.config?.enabled ?? false,
      language: this.config?.language ?? "en",
      stats: {
        ...docStats,
        totalRefs: refStats.totalRefs,
        validRefs: refStats.validRefs,
        brokenRefs: refStats.brokenRefs,
      },
      lastSync: await this.getLastSync(),
    };
  }

  /**
   * Get last sync timestamp (optimized - uses SQL MAX)
   */
  private async getLastSync(): Promise<number | undefined> {
    const maxSync = await this.docStorage.getMaxLastSync();
    return maxSync ?? undefined;
  }

  // ---------------------------------------------------------------------------
  // Document Operations
  // ---------------------------------------------------------------------------

  /**
   * Save a documentation file
   * Optimized: uses batch insert for docs and refs
   */
  async saveDocument(
    filePath: string,
    content: string,
    options: {
      type?: DocEntityType | undefined;
      autoGenerated?: boolean;
      relatedEntityId?: string | undefined;
    } = {},
  ): Promise<DocEntity[]> {
    const parsed = parseMarkdown(content, filePath);
    const sections = flattenSections(parsed.sections);
    const docType = options.type ?? this.inferDocType(filePath);
    const now = Date.now();

    // Delete existing references for this file
    await this.refStorage.deleteRefsBySource(filePath);

    // Prepare all docs for batch upsert
    const docsToSave = sections.map((section) => ({
      type: docType,
      filePath,
      section: section.id,
      title: section.title,
      content: section.content,
      tags: [] as string[],
      autoGenerated: options.autoGenerated ?? true,
      confidence: 1.0,
      lastSync: now,
    }));

    // Batch upsert all docs
    await this.docStorage.upsertDocs(docsToSave);

    // Collect all refs from all sections for batch insert
    const allRefs: Parameters<typeof this.refStorage.createRefs>[0] = [];
    for (const section of sections) {
      for (const ref of section.refs) {
        allRefs.push({
          sourceType: RefSourceType.DOC,
          sourceLocation: {
            filePath,
            lineStart: ref.line,
            lineEnd: ref.line,
            charStart: ref.column,
          },
          targetType: ref.targetType,
          targetId: ref.targetId,
          refType: RefType.DESCRIBES,
          refSyntax: ref.syntax,
          valid: true, // Will be validated later
          targetFilePath: this.extractFilePath(ref.targetId),
          targetLineStart: this.extractLineStart(ref.targetId),
          targetLineEnd: this.extractLineEnd(ref.targetId),
        });
      }
    }

    // Batch create all refs
    if (allRefs.length > 0) {
      await this.refStorage.createRefs(allRefs);
    }

    // Return saved docs (fetch from storage to get IDs)
    return await this.docStorage.getDocsByFile(filePath);
  }

  /**
   * Save a single section within a document
   */
  async saveSectionContent(filePath: string, sectionTitle: string, content: string): Promise<DocEntity | null> {
    const sectionId = this.slugify(sectionTitle);
    const docId = `doc::${filePath}::${sectionId}`;

    return await this.docStorage.updateDoc(docId, {
      content,
      lastSync: Date.now(),
      confidence: 1.0,
    });
  }

  /**
   * Get a document by ID
   */
  async getDocument(docId: string): Promise<DocEntity | null> {
    return await this.docStorage.getDoc(docId);
  }

  /**
   * Get all documents for a file
   */
  async getDocumentsByFile(filePath: string): Promise<DocEntity[]> {
    return await this.docStorage.getDocsByFile(filePath);
  }

  /**
   * Get outdated documents
   */
  async getOutdatedDocs(): Promise<OutdatedDoc[]> {
    return await this.docStorage.getOutdatedDocs(OUTDATED_THRESHOLD);
  }

  /**
   * Get todos (sections needing documentation)
   */
  async getTodos(priority?: "high" | "medium" | "low"): Promise<AutoDocTodo[]> {
    return await this.docStorage.getTodos(priority);
  }

  /**
   * Add a todo item
   */
  async addTodo(todo: Omit<AutoDocTodo, "sectionId">): Promise<void> {
    await this.docStorage.addTodo(todo);
  }

  /**
   * Complete a todo item
   */
  async completeTodo(sectionId: string): Promise<boolean> {
    return await this.docStorage.completeTodo(sectionId);
  }

  /**
   * Get all documents (for search/indexing)
   */
  async getAllDocuments(): Promise<DocEntity[]> {
    return await this.docStorage.getAllDocs();
  }

  /**
   * Search documents by text query (optimized - uses SQL LIKE)
   * Returns documents where title or content contains the query
   */
  async searchDocsByText(query: string, limit = 10): Promise<DocEntity[]> {
    return await this.docStorage.searchByText(query, limit);
  }

  // ---------------------------------------------------------------------------
  // Context Building
  // ---------------------------------------------------------------------------

  /**
   * Get context for documenting an entity
   * Optimized: uses getIncomingRelationships instead of loading all entities
   */
  async getDocContext(
    entityId: string,
    options: {
      includeCode?: boolean;
      includeCallers?: boolean;
      maxCallers?: number;
    } = {},
  ): Promise<DocContext | null> {
    if (!this.graphStorage) {
      return null;
    }

    // Get the entity
    const entity = await this.graphStorage.getEntity(entityId);
    if (!entity) {
      return null;
    }

    const context: DocContext = {};

    // Include entity info
    if (options.includeCode !== false) {
      context.entity = {
        id: entity.id,
        name: entity.name,
        type: entity.type,
        filePath: entity.filePath,
        code: "", // Would need to read file to get code
        signature: entity.metadata?.signature as string | undefined,
      };
    }

    // Include callers - optimized: use getIncomingRelationships if available + parallel fetching
    if (options.includeCallers) {
      const maxCallers = options.maxCallers ?? 10;

      // Get caller relationships
      let callerRels: Array<{ fromId: string; line?: number | undefined }> = [];

      // Try to use getIncomingRelationships if available (more efficient)
      const storageExt = this.graphStorage as GraphStorageWithIncoming;
      if (typeof storageExt.getIncomingRelationships === "function") {
        const incomingRels = await storageExt.getIncomingRelationships(entityId);
        callerRels = incomingRels
          .filter((rel) => rel.type === "calls" || rel.type === "references")
          .slice(0, maxCallers)
          .map((rel) => ({ fromId: rel.fromId, line: rel.metadata?.line }));
      } else {
        // Fallback: Get relationships for target entity directly
        const rels = await this.graphStorage.getRelationshipsForEntity(entityId);
        callerRels = rels
          .filter((rel) => rel.toId === entityId && (rel.type === "calls" || rel.type === "references"))
          .slice(0, maxCallers)
          .map((rel) => ({ fromId: rel.fromId, line: rel.metadata?.line as number | undefined }));
      }

      // Fetch callers in parallel (up to 8 concurrent)
      const callerEntities = await mapParallel(
        callerRels,
        async (rel) => {
          const caller = await this.graphStorage!.getEntity(rel.fromId);
          return caller ? { caller, line: rel.line } : null;
        },
        8,
      );

      context.callers = callerEntities
        .filter((c): c is NonNullable<typeof c> => c !== null)
        .map(({ caller, line }) => ({
          id: caller.id,
          name: caller.name,
          filePath: caller.filePath,
          context: `Line ${line ?? "?"}`,
        }));
    }

    // Include existing documentation
    const existingDocs = await this.refStorage.getRefsByTarget(entityId);
    if (existingDocs.length > 0) {
      const docRef = existingDocs[0];
      if (docRef) {
        const doc = await this.docStorage.getDoc(docRef.sourceLocation.filePath);
        if (doc) {
          context.existingDoc = doc;
        }
      }
    }

    return context;
  }

  // ---------------------------------------------------------------------------
  // Reference Operations
  // ---------------------------------------------------------------------------

  /**
   * Get all references from a file
   */
  async getReferences(filePath: string): Promise<Reference[]> {
    return await this.refStorage.getRefsBySource(filePath);
  }

  /**
   * Get all references to a target
   */
  async getReferencesTo(targetId: string): Promise<Reference[]> {
    return await this.refStorage.getRefsByTarget(targetId);
  }

  /**
   * Get broken references
   */
  async getBrokenReferences(): Promise<Reference[]> {
    return await this.refStorage.getBrokenRefs();
  }

  /**
   * Validate all references
   * Optimized: validates references in parallel (up to 8 concurrent)
   */
  async validateReferences(): Promise<{
    total: number;
    valid: number;
    broken: Array<{ ref: Reference; error: string }>;
  }> {
    const allRefs = await this.getAllReferences();
    const broken: Array<{ ref: Reference; error: string }> = [];

    // Validate in parallel
    const validationResults = await mapParallel(
      allRefs,
      async (ref) => {
        const validation = await this.validateSingleRef(ref);
        return { ref, validation };
      },
      8, // Up to 8 concurrent validations
    );

    // Process results and update storage (must be sequential for DB writes)
    for (const { ref, validation } of validationResults) {
      if (!validation.valid) {
        broken.push({ ref, error: validation.error! });
        await this.refStorage.invalidateRef(ref.id, validation.error!);
      } else if (!ref.valid) {
        // Was invalid, now valid
        await this.refStorage.validateRef(ref.id);
      }
    }

    return {
      total: allRefs.length,
      valid: allRefs.length - broken.length,
      broken,
    };
  }

  /**
   * Get all references (optimized - single query instead of N+1)
   */
  private async getAllReferences(): Promise<Reference[]> {
    return await this.refStorage.getAllRefs();
  }

  /**
   * Validate a single reference
   */
  private async validateSingleRef(ref: Reference): Promise<{ valid: boolean; error?: string }> {
    switch (ref.targetType) {
      case RefTargetType.ENTITY: {
        if (!this.graphStorage) {
          return { valid: true }; // Can't validate without graph
        }
        const entity = await this.graphStorage.getEntity(ref.targetId);
        if (!entity) {
          return { valid: false, error: `Entity not found: ${ref.targetId}` };
        }
        return { valid: true };
      }

      case RefTargetType.DOC: {
        const doc = await this.docStorage.getDoc(ref.targetId);
        if (!doc) {
          return { valid: false, error: `Doc not found: ${ref.targetId}` };
        }
        return { valid: true };
      }

      case RefTargetType.LINE_RANGE:
        // Would need file system access to validate line ranges
        return { valid: true };

      case RefTargetType.COMMIT:
        // Would need git access to validate commits
        return { valid: true };

      default:
        return { valid: true };
    }
  }

  /**
   * Update references when code moves
   */
  async updateReferencesForMove(oldFilePath: string, newFilePath: string, lineDelta = 0): Promise<number> {
    // Find all references pointing to the old file
    const refs = await this.refStorage.getRefsByTarget(oldFilePath);
    let updated = 0;

    for (const ref of refs) {
      const newTargetId = ref.targetId.replace(oldFilePath, newFilePath);
      await this.refStorage.updateRef(ref.id, {
        targetId: newTargetId,
        targetFilePath: newFilePath,
      });
      updated++;
    }

    // Update line numbers if there's a delta
    if (lineDelta !== 0) {
      updated += await this.refStorage.updateTargetLines(newFilePath, 0, lineDelta);
    }

    return updated;
  }

  // ---------------------------------------------------------------------------
  // Code Change Handling
  // ---------------------------------------------------------------------------

  /**
   * Handle code entity modification
   */
  async onEntityModified(entityId: string, changeType: ChangeType): Promise<void> {
    // Find all docs that reference this entity
    const refs = await this.refStorage.getRefsByTarget(entityId);

    for (const ref of refs) {
      // Mark the source document as potentially outdated
      const docId = `doc::${ref.sourceLocation.filePath}`;
      await this.docStorage.markOutdated(docId, `Referenced entity ${changeType}: ${entityId}`);
    }

    // Record in changelog
    await this.docStorage.recordChange({
      timestamp: Date.now(),
      branch: "main", // Would get from git
      summary: `Entity ${changeType}: ${entityId}`,
      changes: [
        {
          entityId,
          changeType,
          summary: `Entity was ${changeType}`,
        },
      ],
      impactedDocs: refs.map((r) => `doc::${r.sourceLocation.filePath}`),
    });
  }

  /**
   * Handle file move/rename
   */
  async onFileRenamed(oldPath: string, newPath: string): Promise<void> {
    // Update references
    await this.updateReferencesForMove(oldPath, newPath);

    // Update doc file paths if it's a .md file
    if (oldPath.endsWith(".md")) {
      const docs = await this.docStorage.getDocsByFile(oldPath);
      // Simplified: doc paths not re-created on rename (docs regenerated on next sync)
      void docs;
    }
  }

  /**
   * Get changelog entries
   */
  async getChangelog(
    options: { since?: number | undefined; limit?: number; branch?: string | undefined } = {},
  ): Promise<any[]> {
    return await this.docStorage.getChangelog(options);
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /**
   * Infer document type from file path
   */
  private inferDocType(filePath: string): DocEntityType {
    const normalizedPath = filePath.toLowerCase();

    if (normalizedPath.includes("architecture")) return "architecture" as DocEntityType;
    if (normalizedPath.includes("flow")) return "flow" as DocEntityType;
    if (normalizedPath.includes("process")) return "process" as DocEntityType;
    if (normalizedPath.includes("dependenc")) return "dependency" as DocEntityType;
    if (normalizedPath.includes("deploy")) return "deployment" as DocEntityType;
    if (normalizedPath.includes("glossary")) return "glossary" as DocEntityType;
    if (normalizedPath.includes("_index")) return "module_index" as DocEntityType;

    return "entity_doc" as DocEntityType;
  }

  /**
   * Extract file path from target ID
   */
  private extractFilePath(targetId: string): string | undefined {
    // Handle formats like "file.ts:L25-L50" or "file.ts#L25"
    const match = targetId.match(/^([^:#]+)/);
    return match ? match[1] : undefined;
  }

  /**
   * Extract line start from target ID
   */
  private extractLineStart(targetId: string): number | undefined {
    const match = targetId.match(/:?L(\d+)/);
    return match?.[1] ? parseInt(match[1], 10) : undefined;
  }

  /**
   * Extract line end from target ID
   */
  private extractLineEnd(targetId: string): number | undefined {
    const match = targetId.match(/-L?(\d+)$/);
    return match?.[1] ? parseInt(match[1], 10) : this.extractLineStart(targetId);
  }

  /**
   * Slugify text for IDs
   */
  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_-]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }

  // ---------------------------------------------------------------------------
  // Cleanup
  // ---------------------------------------------------------------------------

  /**
   * Clear all AutoDoc data
   */
  async clear(): Promise<void> {
    await this.docStorage.clear();
    await this.refStorage.clear();
  }

  /**
   * Destroy and clean up resources
   */
  async destroy(): Promise<void> {
    await this.docStorage.destroy();
    await this.refStorage.destroy();
    this.initialized = false;
    this.config = null;
    this.graphStorage = null;
  }
}

// =============================================================================
// 3. FACTORY FUNCTION
// =============================================================================

let instance: AutoDocManager | null = null;

/**
 * Get or create the AutoDoc manager singleton
 * @param dbPath - Path to SQLite database file for autodoc storage
 */
export function getAutoDocManager(dbPath: string): AutoDocManager {
  if (!instance) {
    instance = new AutoDocManager(dbPath);
  }
  return instance;
}

/**
 * Reset the AutoDoc manager singleton
 */
export async function resetAutoDocManager(): Promise<void> {
  if (instance) {
    await instance.destroy();
    instance = null;
  }
}
