/**
 * Embedding Processor Module
 *
 * Handles entity embedding generation and storage.
 * Extracted from semantic-agent.ts for better modularity.
 *
 * Main responsibilities:
 * - Filter entities for embedding generation
 * - Handle pre-generated embeddings from workers
 * - Build embedding texts with enhanced metadata
 * - Deduplicate texts and check caches
 * - Generate embeddings in batches
 * - Store embeddings in vector store
 */

import { log } from "../../logging/index.js";
import type { EmbeddingGenerator } from "../../semantic/embedding-generator.js";
import type { GlobalEmbeddingCache } from "../../semantic/global-embedding-cache.js";
import type { VectorStore } from "../../semantic/vector-store.js";
import type { ParsedEntity } from "../../types/parser.js";
import type { SemanticMetrics, VectorEmbedding } from "../../types/semantic.js";
import { hashText } from "../../utils/fast-hash.js";

/**
 * ParsedEntity with pre-generated embedding from worker
 */
interface ParsedEntityWithEmbedding extends ParsedEntity {
  embeddingBase64?: string;
  embeddingText?: string;
}

// =============================================================================
// CONSTANTS
// =============================================================================

/**
 * Path patterns to EXCLUDE from embedding generation only
 * (entities are still indexed for LSP/navigation)
 *
 * Machine-generated code is indexed for import resolution, call graphs, etc.
 * but excluded from semantic search embeddings because:
 * - High volume (thousands of entities per file)
 * - Low value for semantic search (auto-generated code patterns)
 * - Significantly increases generation time
 */
export const EMBEDDING_EXCLUDE_PATTERNS = [
  "src/generated/", // ANTLR parsers (Java20Parser.ts, RustParser.ts, etc.)
  "/autogenerated/", // Common auto-generated code directory
  "/node_modules/", // Third-party dependencies
  "/__generated__/", // GraphQL / OpenAPI codegen output
  "/.cache/", // Build/tooling caches
  "/dist/", // Compiled output
];

// =============================================================================
// CONTEXT INTERFACE
// =============================================================================

/**
 * Context for embedding processing
 * Allows dependency injection from SemanticAgent
 */
export interface EmbeddingProcessorContext {
  // Core components
  embeddingGen: EmbeddingGenerator;
  vectorStore: VectorStore;
  globalCache: GlobalEmbeddingCache | null;

  // Configuration
  embeddingDim: number;
  embeddingBatchSize: number;
  twoPhaseMode: boolean;

  // State
  dumpBatchIndex: number;
  semanticMetrics: SemanticMetrics;

  // Mutex for thread safety
  embeddingMutex: Promise<void>;
  setEmbeddingMutex: (p: Promise<void>) => void;

  // Callbacks
  onDumpBatchIndexIncrement: () => void;
  onMetricsUpdate: (count: number) => void;
  onVectorsStoredUpdate: () => Promise<void>;
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Check if a file path matches any exclude pattern
 */
export function shouldExcludeFromEmbedding(filePath: string): boolean {
  const normalizedPath = filePath.replace(/\\/g, "/");
  for (const pattern of EMBEDDING_EXCLUDE_PATTERNS) {
    if (normalizedPath.includes(pattern)) {
      return true;
    }
  }
  return false;
}

/**
 * Determine if an entity is too trivial to embed.
 *
 * Trivial entities add noise to the vector index and waste generation time.
 * We skip them when they satisfy ALL of:
 *   - Very short body (≤2 lines of code)
 *   - No outgoing calls (pure assignment / return)
 *   - No control-flow branches or loops
 *   - No JSDoc / inline description
 *
 * Typical examples: bare getters, setters, single-return delegators.
 * If ANY signal of semantic value is present the entity is kept.
 */
export function isTrivialEntity(entity: ParsedEntity): boolean {
  const loc = entity.complexity?.linesOfCode ?? 0;
  if (loc === 0) return false; // Unknown size — keep to be safe

  const hasCalls = (entity.calls?.length ?? 0) > 0;
  const cf = entity.controlFlow;
  const hasFlow = (cf?.branches?.length ?? 0) + (cf?.loops?.length ?? 0) + (cf?.exceptions?.length ?? 0) > 0;
  const hasDoc = !!entity.documentation?.description;

  if (hasCalls || hasFlow || hasDoc) return false;

  // Pure trivial: ≤2 LOC, no outgoing calls, no flow, no docs
  return loc <= 2;
}

/**
 * Build enhanced text for embedding from entity data
 */
export function buildEmbeddingText(entity: ParsedEntity, code: string): string {
  const parts: string[] = [];

  // Header
  const header = `${entity.name ?? ""} ${entity.type ?? ""} ${entity.signature ?? ""}`.trim();
  if (header) parts.push(header);

  // Add documentation if available (improves semantic search by description)
  if (entity.documentation?.description) {
    parts.push(`description: ${entity.documentation.description}`);
  }

  // Add call information (enables "find functions that call X" queries)
  if (entity.calls && entity.calls.length > 0) {
    const callsToProcess = entity.calls.length > 20 ? entity.calls.slice(0, 20) : entity.calls;
    const callParts: string[] = [];
    for (const c of callsToProcess) {
      if (!c) continue;
      callParts.push(c.target ? `${c.target}.${c.name || ""}` : c.name || "");
    }
    if (callParts.length > 0) {
      parts.push(`calls: ${callParts.join(", ")}`);
    }
  }

  // Add complexity info (enables "find complex functions" queries)
  if (entity.complexity) {
    const cx = entity.complexity;
    if (cx.cyclomatic > 5 || cx.cognitive > 10) {
      parts.push(`complexity: cyclomatic=${cx.cyclomatic} cognitive=${cx.cognitive}`);
    }
  }

  // Add control flow summary (enables "find functions with try-catch" queries)
  if (entity.controlFlow) {
    const cf = entity.controlFlow;
    const flowParts: string[] = [];
    if (cf.branches?.length > 0) flowParts.push(`branches=${cf.branches.length}`);
    if (cf.loops?.length > 0) flowParts.push(`loops=${cf.loops.length}`);
    if (cf.exceptions?.length > 0) flowParts.push(`exceptions=${cf.exceptions.length}`);
    if (cf.awaits?.length > 0) flowParts.push(`awaits=${cf.awaits.length}`);
    if (flowParts.length > 0) {
      parts.push(`flow: ${flowParts.join(", ")}`);
    }
  }

  // Add return type for better type-based search
  if (entity.returnType) {
    parts.push(`returns: ${entity.returnType}`);
  }

  // Add parameter types for signature-based search
  if (entity.parameters && entity.parameters.length > 0) {
    const paramParts: string[] = [];
    for (const p of entity.parameters) {
      if (p.type && paramParts.length < 10) {
        paramParts.push(`${p.name}:${p.type}`);
      }
    }
    if (paramParts.length > 0) {
      parts.push(`params: ${paramParts.join(", ")}`);
    }
  }

  // Add the code
  if (code) {
    parts.push(code);
  }

  return parts.join("\n").trim();
}

/**
 * Build vector embedding metadata from entity
 */
export function buildVectorMetadata(entity: ParsedEntity, modelName: string): Record<string, unknown> {
  const metadata: Record<string, unknown> = {
    path: entity.filePath ?? entity.path ?? "",
    type: entity.type,
    name: entity.name,
    language: entity.language ?? undefined,
    entityId: entity.id ?? undefined,
    start: entity.location?.start?.index ?? undefined,
    end: entity.location?.end?.index ?? undefined,
    model: modelName,
  };

  // Add complexity metrics (enables filtering by complexity)
  if (entity.complexity) {
    metadata["cyclomatic"] = entity.complexity.cyclomatic;
    metadata["cognitive"] = entity.complexity.cognitive;
    metadata["linesOfCode"] = entity.complexity.linesOfCode;
    metadata["nestingDepth"] = entity.complexity.nestingDepth;
  }

  // Add call count (enables "find functions with many calls" queries)
  if (entity.calls?.length) {
    metadata["callCount"] = entity.calls.length;
    metadata["hasAsyncCalls"] = entity.calls.some((c) => c.isAwait);
  }

  // Add control flow flags (enables filtering)
  if (entity.controlFlow) {
    const cf = entity.controlFlow;
    metadata["hasBranches"] = (cf.branches?.length || 0) > 0;
    metadata["hasLoops"] = (cf.loops?.length || 0) > 0;
    metadata["hasExceptions"] = (cf.exceptions?.length || 0) > 0;
    metadata["hasAwaits"] = (cf.awaits?.length || 0) > 0;
    metadata["branchCount"] = cf.branches?.length || 0;
    metadata["loopCount"] = cf.loops?.length || 0;
    metadata["returnCount"] = cf.returns?.length || 0;
  }

  // Add documentation flag (enables "find documented functions" queries)
  if (entity.documentation) {
    metadata["hasDocumentation"] = true;
    metadata["hasParams"] = (entity.documentation.params?.length || 0) > 0;
    metadata["hasExamples"] = (entity.documentation.examples?.length || 0) > 0;
    metadata["isDeprecated"] = !!entity.documentation.deprecated;
  }

  // Add return type for type-based filtering
  if (entity.returnType) {
    metadata["returnType"] = entity.returnType;
  }

  // Add parameter count
  if (entity.parameters?.length) {
    metadata["paramCount"] = entity.parameters.length;
  }

  return metadata;
}

// =============================================================================
// PRE-GENERATED EMBEDDING PROCESSING
// =============================================================================

/**
 * Process entities with pre-generated embeddings from workers
 */
export async function processPreGeneratedEmbeddings(
  entities: ParsedEntity[],
  ctx: Pick<EmbeddingProcessorContext, "vectorStore" | "onMetricsUpdate">,
  modelName: string,
): Promise<{ processed: number; failed: ParsedEntity[] }> {
  const failedEntities: ParsedEntity[] = [];
  const vectorEmbeddings: VectorEmbedding[] = [];

  for (const entity of entities) {
    const e = entity as ParsedEntityWithEmbedding;
    try {
      // Decode base64 to Float32Array
      const binaryData = Buffer.from(e.embeddingBase64!, "base64");
      const vector = new Float32Array(binaryData.buffer, binaryData.byteOffset, binaryData.length / 4);

      // Build stable ID
      const stableId = e.id
        ? `ent:${e.id}`
        : `doc:${hashText(`${e.filePath ?? ""}|${e.type}|${e.name ?? "anon"}|${modelName}`).slice(0, 24)}`;

      vectorEmbeddings.push({
        id: stableId,
        content: e.embeddingText ?? `${e.name ?? ""} ${e.type ?? ""}`.trim(),
        vector,
        metadata: buildVectorMetadata(e, modelName),
        createdAt: Date.now(),
      });
    } catch (error) {
      log.w("EMBEDDING", `Failed to decode pre-generated embedding`, {
        entityId: e.id,
        name: e.name,
        error: (error as Error).message,
      });
      failedEntities.push(entity);
    }
  }

  if (vectorEmbeddings.length > 0) {
    const insertResult = await ctx.vectorStore.adaptiveBulkInsert(vectorEmbeddings);
    log.i("EMBEDDING", `Inserted pre-generated embeddings`, {
      count: vectorEmbeddings.length,
      timeMs: insertResult.timeMs.toFixed(1),
    });
    ctx.onMetricsUpdate(vectorEmbeddings.length);
  }

  return { processed: vectorEmbeddings.length, failed: failedEntities };
}

// =============================================================================
// TEXT DEDUPLICATION AND CACHE CHECK
// =============================================================================

export interface DeduplicationResult {
  uniqueTexts: string[];
  originalIndexToHash: string[];
  seenHashes: Map<string, number>;
  cacheHits: Map<string, Float32Array>;
  textsNeedingGeneration: string[];
  textsNeedingGenerationHashes: string[];
  globalCacheHitCount: number;
  persistentCacheHitCount: number;
}

/**
 * Deduplicate texts and check caches
 */
export async function deduplicateAndCheckCaches(
  texts: string[],
  ctx: EmbeddingProcessorContext,
  getLibSQLAdapter: () => any,
): Promise<DeduplicationResult> {
  const seenHashes = new Map<string, number>();
  const originalIndexToHash: string[] = new Array(texts.length);
  const uniqueTexts: string[] = [];

  const cacheHits = new Map<string, Float32Array>();
  const uncachedTexts: string[] = [];
  const uncachedHashes: string[] = [];

  const textsNeedingGeneration: string[] = [];
  const textsNeedingGenerationHashes: string[] = [];

  // Single pass: deduplicate AND check in-memory cache
  for (let i = 0; i < texts.length; i++) {
    const text = texts[i]!;
    const textHash = hashText(text).slice(0, 16);
    originalIndexToHash[i] = textHash;

    if (!seenHashes.has(textHash)) {
      seenHashes.set(textHash, uniqueTexts.length);
      uniqueTexts.push(text);

      // Check in-memory cache immediately
      const globalHit = ctx.globalCache?.get(text);
      if (globalHit) {
        cacheHits.set(textHash, globalHit);
      } else {
        uncachedTexts.push(text);
        uncachedHashes.push(textHash);
      }
    }
  }
  const globalCacheHitCount = cacheHits.size;

  // Check persistent cache in LibSQL
  let persistentCacheHitCount = 0;
  const libsqlAdapter = getLibSQLAdapter();
  if (libsqlAdapter && uncachedHashes.length > 0) {
    try {
      const persistentHits = await libsqlAdapter.getEmbeddingsFromCache(uncachedHashes);
      for (let i = 0; i < uncachedHashes.length; i++) {
        const hash = uncachedHashes[i]!;
        const embedding = persistentHits.get(hash);
        if (embedding) {
          cacheHits.set(hash, embedding);
          ctx.globalCache?.set(uncachedTexts[i]!, embedding);
          persistentCacheHitCount++;
        } else {
          textsNeedingGeneration.push(uncachedTexts[i]!);
          textsNeedingGenerationHashes.push(hash);
        }
      }
      if (persistentCacheHitCount > 0) {
        log.i("EMBCACHE", "Batch hits", {
          checked: uncachedHashes.length,
          hits: persistentCacheHitCount,
          remaining: textsNeedingGeneration.length,
        });
      }
    } catch (error) {
      log.w("EMBCACHE", "Batch lookup failed", { error: (error as Error).message });
      textsNeedingGeneration.push(...uncachedTexts);
      textsNeedingGenerationHashes.push(...uncachedHashes);
    }
  } else {
    textsNeedingGeneration.push(...uncachedTexts);
    textsNeedingGenerationHashes.push(...uncachedHashes);
  }

  return {
    uniqueTexts,
    originalIndexToHash,
    seenHashes,
    cacheHits,
    textsNeedingGeneration,
    textsNeedingGenerationHashes,
    globalCacheHitCount,
    persistentCacheHitCount,
  };
}

// =============================================================================
// EMBEDDING GENERATION
// =============================================================================

/**
 * Generate embeddings for texts not in cache
 */
export async function generateEmbeddings(
  dedup: DeduplicationResult,
  ctx: EmbeddingProcessorContext,
  modelName: string,
  getLibSQLAdapter: () => any,
): Promise<Map<string, Float32Array>> {
  const hashToEmbedding = new Map<string, Float32Array>(dedup.cacheHits);

  if (dedup.textsNeedingGeneration.length > 0) {
    log.t("EMBEDDING", "Before generateBatch", { count: dedup.textsNeedingGeneration.length });
    const generatedEmbeddings = await ctx.embeddingGen.generateBatch(dedup.textsNeedingGeneration);
    log.t("EMBEDDING", "After generateBatch", { count: generatedEmbeddings.length });

    // Map generated embeddings by hash
    for (let i = 0; i < dedup.textsNeedingGenerationHashes.length; i++) {
      hashToEmbedding.set(dedup.textsNeedingGenerationHashes[i]!, generatedEmbeddings[i]!);
    }

    // Save to persistent cache (fire-and-forget)
    const persistAdapter = getLibSQLAdapter();
    if (persistAdapter) {
      const cacheEntries = dedup.textsNeedingGenerationHashes.map((hash, i) => ({
        contentHash: hash,
        model: modelName,
        embedding: generatedEmbeddings[i]!,
        textPreview: dedup.textsNeedingGeneration[i]?.slice(0, 100),
      }));
      persistAdapter.setEmbeddingsInCache(cacheEntries).catch((err: Error) => {
        log.w("EMBCACHE", "Failed to save embeddings", { error: err.message });
      });
      log.d("EMBCACHE", "Saving new embeddings", { count: cacheEntries.length });
    }
  } else {
    const totalCacheHits = dedup.globalCacheHitCount + dedup.persistentCacheHitCount;
    log.i("EMBCACHE", "100% cache hit", { count: totalCacheHits });
  }

  return hashToEmbedding;
}
