/**
 * AutoDoc Type Definitions
 *
 * Types for automatic documentation layer with semantic search.
 * Provides interfaces for doc entities, references, changelog, and tasks.
 *
 * Architecture References:
 * - Storage Types: src/types/storage.ts
 * - RFC: docs/design/documentation-layer-rfc.md
 */

// =============================================================================
// 1. ENUMS AND CONSTANTS
// =============================================================================

/**
 * Types of documentation entities
 */
export enum DocEntityType {
  /** Project architecture overview */
  ARCHITECTURE = "architecture",
  /** Business scenarios (user stories) */
  FLOW = "flow",
  /** Technical processes */
  PROCESS = "process",
  /** External dependencies */
  DEPENDENCY = "dependency",
  /** Deployment and CI/CD */
  DEPLOYMENT = "deployment",
  /** Glossary terms */
  GLOSSARY = "glossary",
  /** Module index (_index.md) */
  MODULE_INDEX = "module_index",
  /** Entity-level documentation */
  ENTITY_DOC = "entity_doc",
  /** Generic section */
  SECTION = "section",
}

/**
 * Types of references between docs and code
 */
export enum RefType {
  /** Documentation describes code entity */
  DESCRIBES = "describes",
  /** Documentation depends on another doc */
  DEPENDS = "depends",
  /** Code example reference */
  EXAMPLE = "example",
  /** Test reference */
  TEST = "test",
  /** Process/flow participation */
  PARTICIPATES = "participates",
  /** Consumer relationship */
  USES = "uses",
}

/**
 * Source types for references
 */
export enum RefSourceType {
  /** Reference from MD documentation */
  DOC = "doc",
  /** Reference from code comment */
  COMMENT = "comment",
  /** Reference from code (imports, calls) */
  CODE = "code",
}

/**
 * Target types for references
 */
export enum RefTargetType {
  /** Target is a code entity (AST) */
  ENTITY = "entity",
  /** Target is a documentation file/section */
  DOC = "doc",
  /** Target is a line range in file */
  LINE_RANGE = "line_range",
  /** Target is a git commit */
  COMMIT = "commit",
}

/**
 * Change types for changelog
 */
export enum ChangeType {
  ADDED = "added",
  MODIFIED = "modified",
  DELETED = "deleted",
  MOVED = "moved",
}

/**
 * Supported documentation languages
 */
export type DocLanguage = "en" | "ru" | "zh";

// =============================================================================
// 2. LOCATION TYPES
// =============================================================================

/**
 * Source location in a file
 */
export interface SourceLocation {
  filePath: string;
  lineStart: number;
  lineEnd: number;
  charStart?: number;
  charEnd?: number;
}

/**
 * Section location within MD file
 */
export interface SectionLocation {
  /** Heading level (1-6) */
  level: number;
  /** Section title from heading */
  title: string;
  /** Line number where section starts */
  lineStart: number;
  /** Line number where section ends */
  lineEnd: number;
}

// =============================================================================
// 3. CORE ENTITY TYPES
// =============================================================================

/**
 * Documentation entity stored in database
 */
export interface DocEntity {
  /** Unique ID: doc::{filePath}::{sectionId} */
  id: string;
  /** Type of documentation */
  type: DocEntityType;
  /** Path to .md file relative to .autodoc/ */
  filePath: string;
  /** Section within file (null for whole file) */
  section: string | null;
  /** Section title */
  title: string;
  /** Section content (markdown) */
  content: string;
  /** Tags for categorization */
  tags: string[];
  /** Whether AI-generated (vs human-written) */
  autoGenerated: boolean;
  /** AI confidence in content accuracy (0-1) */
  confidence: number;
  /** Last sync with code timestamp */
  lastSync: number;
  /** Creation timestamp */
  createdAt: number;
  /** Last update timestamp */
  updatedAt: number;
}

/**
 * Reference linking docs, code, and comments
 */
export interface Reference {
  /** Unique ID */
  id: string;
  /** Source type (doc, comment, code) */
  sourceType: RefSourceType;
  /** Source location */
  sourceLocation: SourceLocation;
  /** Target type */
  targetType: RefTargetType;
  /** Target identifier (entity ID, doc ID, or file:L1-L50) */
  targetId: string;
  /** Reference type (describes, depends, etc.) */
  refType: RefType;
  /** Original syntax of the reference */
  refSyntax: string;
  /** Whether reference is valid */
  valid: boolean;
  /** Validation error if invalid */
  validationError?: string | undefined;
  /** Creation timestamp */
  createdAt: number;
  /** Last update timestamp */
  updatedAt: number;

  // Denormalized fields for fast querying
  /** Target entity ID if applicable */
  targetEntityId?: string | undefined;
  /** Target file path */
  targetFilePath?: string | undefined;
  /** Target line start */
  targetLineStart?: number | undefined;
  /** Target line end */
  targetLineEnd?: number | undefined;
}

/**
 * Changelog entry for tracking documentation changes
 */
export interface ChangeLogEntry {
  /** Unique ID */
  id: string;
  /** Timestamp of change */
  timestamp: number;
  /** Git commit hash if available */
  commitHash?: string | undefined;
  /** Git branch name */
  branch: string;
  /** Human-readable summary */
  summary?: string | undefined;
  /** Detailed changes */
  changes: Array<{
    entityId: string;
    changeType: ChangeType;
    summary: string;
    diffHighlights?: string[];
  }>;
  /** IDs of documentation requiring update */
  impactedDocs: string[];
}

/**
 * Comment reference extracted from code
 */
export interface CommentRef {
  /** Unique ID: comment::{filePath}::{lineStart} */
  id: string;
  /** Source file path */
  filePath: string;
  /** Comment start line */
  lineStart: number;
  /** Comment end line */
  lineEnd: number;
  /** Comment content */
  content: string;
  /** Parent code entity ID if associated */
  parentEntityId?: string;
  /** Extracted doc references (@see docs://...) */
  docRefs: string[];
  /** Extracted entity references (@see entity:...) */
  entityRefs: string[];
  /** Flow tags (@flow tag1, tag2) */
  flowTags: string[];
  /** Creation timestamp */
  createdAt: number;
  /** Last update timestamp */
  updatedAt: number;
}

// =============================================================================
// 4. CONFIGURATION AND SETTINGS
// =============================================================================

/**
 * AutoDoc configuration stored in marker file
 */
export interface AutoDocConfig {
  /** Whether AutoDoc is enabled */
  enabled: boolean;
  /** Documentation language */
  language: DocLanguage;
  /** Directory for documentation files */
  docsDir?: string;
  /** When AutoDoc was initialized */
  created?: string;
  /** Absolute path to project */
  projectPath?: string | undefined;
}

/**
 * Project status returned by autodoc_status
 */
export interface AutoDocStatus {
  /** Whether enabled */
  enabled: boolean;
  /** Documentation language */
  language: DocLanguage;
  /** Statistics */
  stats: {
    /** Total documentation files */
    totalDocs: number;
    /** Total sections */
    totalSections: number;
    /** Sections filled */
    filledSections: number;
    /** Sections needing update */
    outdatedSections: number;
    /** Total references */
    totalRefs: number;
    /** Valid references */
    validRefs: number;
    /** Broken references */
    brokenRefs: number;
  };
  /** When last synced */
  lastSync?: number | undefined;
}

/**
 * Todo item for AI to fill
 */
export interface AutoDocTodo {
  /** Section identifier */
  sectionId: string;
  /** File path */
  filePath: string;
  /** Section title */
  title: string;
  /** Priority level */
  priority: "high" | "medium" | "low";
  /** Why this section is important */
  reason: string;
  /** Related entity ID if applicable */
  relatedEntityId?: string | undefined;
}

// =============================================================================
// 5. SEARCH AND QUERY TYPES
// =============================================================================

/**
 * Search result item
 */
export interface DocSearchResult {
  /** Document/section ID */
  id: string;
  /** Result type */
  type: "doc" | "code" | "comment";
  /** Title */
  title: string;
  /** Content snippet */
  snippet: string;
  /** Relevance score (0-1) */
  score: number;
  /** File path */
  filePath: string;
  /** Section if applicable */
  section?: string | undefined;
  /** Line range if applicable */
  lineRange?: { start: number; end: number };
  /** Code references */
  codeRefs?: Array<{
    entityId: string;
    filePath: string;
    lineStart: number;
    lineEnd: number;
  }>;
}

/**
 * Context for AI documentation writing
 */
export interface DocContext {
  /** Entity being documented */
  entity?: {
    id: string;
    name: string;
    type: string;
    filePath: string;
    code: string;
    signature?: string | undefined;
  };
  /** Callers of this entity */
  callers?: Array<{
    id: string;
    name: string;
    filePath: string;
    context: string;
  }>;
  /** Dependencies of this entity */
  dependencies?: Array<{
    id: string;
    name: string;
    type: string;
  }>;
  /** Existing documentation */
  existingDoc?: DocEntity;
  /** Related documentation */
  relatedDocs?: DocEntity[];
  /** Processes this entity participates in */
  processes?: string[];
}

/**
 * Outdated documentation item
 */
export interface OutdatedDoc {
  /** Document ID */
  docId: string;
  /** File path */
  filePath: string;
  /** Section */
  section?: string | undefined;
  /** Reason for being outdated */
  reason: string;
  /** Related code changes */
  codeChanges?: Array<{
    entityId: string;
    changeType: ChangeType;
    summary: string;
  }>;
  /** Current confidence level */
  confidence: number;
}

// =============================================================================
// 6. PARSING TYPES
// =============================================================================

/**
 * Parsed markdown section
 */
export interface ParsedSection {
  /** Section ID (slugified title) */
  id: string;
  /** Heading level (1-6) */
  level: number;
  /** Section title */
  title: string;
  /** Raw markdown content */
  content: string;
  /** Line range in source file */
  lineStart: number;
  lineEnd: number;
  /** Extracted references */
  refs: ParsedReference[];
  /** Child sections */
  children: ParsedSection[];
}

/**
 * Parsed reference from markdown
 */
export interface ParsedReference {
  /** Original syntax: [→ text](target) */
  syntax: string;
  /** Display text */
  text: string;
  /** Target URL/path */
  target: string;
  /** Parsed target type */
  targetType: RefTargetType;
  /** Parsed target ID */
  targetId: string;
  /** Line number in source */
  line: number;
  /** Character position */
  column: number;
}

/**
 * Parsed markdown document
 */
export interface ParsedDocument {
  /** File path */
  filePath: string;
  /** Document title (first H1) */
  title: string;
  /** All sections */
  sections: ParsedSection[];
  /** All references (flattened) */
  allRefs: ParsedReference[];
  /** Parse errors if any */
  errors?: string[];
}

// =============================================================================
// 7. TOOL PARAMETER TYPES
// =============================================================================

/**
 * Parameters for autodoc_init
 */
export interface InitParams {
  language: DocLanguage;
  createTemplates?: boolean;
}

/**
 * Parameters for autodoc_save
 */
export interface SaveParams {
  filePath: string;
  content: string;
  entityId?: string | undefined;
}

/**
 * Parameters for autodoc_save_section
 */
export interface SaveSectionParams {
  filePath: string;
  section: string;
  content: string;
}

/**
 * Parameters for autodoc_search
 */
export interface SearchParams {
  query: string;
  scope?: "all" | "code" | "docs";
  limit?: number;
}

/**
 * Parameters for autodoc_get_context
 */
export interface GetContextParams {
  entityId: string;
  includeCode?: boolean;
  includeCallers?: boolean;
}

/**
 * Parameters for autodoc_validate
 */
export interface ValidateParams {
  fixBrokenRefs?: boolean;
}

/**
 * Parameters for autodoc_changelog
 */
export interface ChangelogParams {
  since?: string | undefined;
  entityId?: string | undefined;
  limit?: number;
}

// =============================================================================
// 8. RESULT TYPES
// =============================================================================

/**
 * Result of autodoc_init
 */
export interface InitResult {
  success: boolean;
  /** Created files */
  createdFiles: string[];
  /** Work plan for AI */
  workPlan: {
    totalSections: number;
    highPriority: AutoDocTodo[];
    mediumPriority: AutoDocTodo[];
    lowPriority: AutoDocTodo[];
  };
  /** Error message if failed */
  error?: string;
}

/**
 * Result of autodoc_save
 */
export interface SaveResult {
  success: boolean;
  /** Saved document ID */
  docId?: string;
  /** Extracted references */
  extractedRefs?: number;
  /** Validation warnings */
  warnings?: string[];
  /** Error message if failed */
  error?: string;
}

/**
 * Result of autodoc_validate
 */
export interface ValidateResult {
  /** Total references checked */
  totalRefs: number;
  /** Valid references */
  validRefs: number;
  /** Broken references */
  brokenRefs: Array<{
    refId: string;
    sourceFile: string;
    targetId: string;
    error: string;
  }>;
  /** Fixed references (if fixBrokenRefs=true) */
  fixedRefs?: number;
}
